TRUSTED_UPLOADERS = ['HorribleSubs|'
                     'AnimeRG|'
                     'Krosis|'
                     'Dmcs-Fansubs|'
                     'Ohys-Raws|'
                     'PuyaSubs!|'
                     'FUM|'
                     'DIMENSION|'
                     'PODO|'
                     'ROVERS']
